### ISSUE TITLE
[travis][P006] Clojure solution doesn't execute at travis server, curious

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/ProjectEuler#14]
The [log](https://travis-ci.org/DestructHub/ProjectEuler/builds/115651242) show us that:

```
$ python stats.py --search python --build --search commonlisp --search ruby --search haskell --search clojure --search go --search php --search python --search elixir --search lua --search bash

Command: Search Build

Builded Problem001/Clojure/solution_1.clj: Answer: 233168: 1.10s

Builded Problem002/Clojure/solution_1.clj: Answer: 4613732: 0.58s

@Building next Problem006/Clojure/solution_1.clj:  Exception in thread "main" java.lang.ClassCastException: clojure.lang.Symbol cannot be cast to java.lang.Number (solution_1.clj:0)

    at clojure.lang.Compiler.eval(Compiler.java:4658)

    at clojure.lang.Compiler.load(Compiler.java:4972)

    at clojure.lang.Compiler.loadFile(Compiler.java:4939)

    at clojure.main$load_script__7405.invoke(main.clj:213)

    at clojure.main$script_opt__7442.invoke(main.clj:265)

    at clojure.main$main__7466.doInvoke(main.clj:346)

    at clojure.lang.RestFn.invoke(RestFn.java:413)

    at clojure.lang.Var.invoke(Var.java:359)

    at clojure.lang.AFn.applyToHelper(AFn.java:173)

    at clojure.lang.Var.applyTo(Var.java:476)

    at clojure.main.main(main.java:37)

Caused by: java.lang.ClassCastException: clojure.lang.Symbol cannot be cast to java.lang.Number

    at clojure.lang.Numbers.add(Numbers.java:123)

    at clojure.core$_PLUS___4509.invoke(core.clj:683)

    at clojure.core$reduce__4500.invoke(core.clj:668)

    at clojure.core$reduce__4500.invoke(core.clj:659)

    at user$solve__1.invoke(solution_1.clj:2)

    at user$eval__4.invoke(solution_1.clj:6)

    at clojure.lang.Compiler.eval(Compiler.java:4642)

    ... 10 more

(⣽) t: 0.521
```

Hmm, I'm curious with that because in my machine execute fines that solution at Clojure 1.8.

**Comment by ryukinix** [comment]
Clojure is executing ok on the new build using docker. Closing this. Look at #117
